trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: "Install Veracode CLI & Package Source Code"
  inputs:
    targetType: 'inline'
    script: |
      # Install Veracode CLI
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      # Package the entire source directory
      ./veracode package -das $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)/verascan

      # Check if the package exists
      if [ ! -d "$(Build.ArtifactStagingDirectory)/verascan" ]; then
        echo "Error: verascan directory not found."
        exit 1
      fi
  env:
    VERACODE_API_KEY_ID: $(VID)
    VERACODE_API_KEY_SECRET: $(VKEY)

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '$(VID)'
    apiKey: '$(VKEY)'
    veracodeAppProfile: 'Recent'
    version: '$(build.buildNumber)'
    filepath: 'verascan/veracode-auto-pack-s-sql.zip'
    importResults: true
    maximumWaitTime: '360'


