trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    ./veracode package -das $(Build.SourcesDirectory) --output ./verascan

    # Check if the verascan directory exists
    if [ ! -d "./verascan" ]; then
      echo "Error: verascan directory not found."
      exit 1
    fi
  displayName: "Install Veracode CLI, Package Code, and Verify Output"
  env:
    VERACODE_API_KEY_ID: $(VID)
    VERACODE_API_KEY_SECRET: $(VKEY)

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    veracodeAppProfile: 'Recent'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    importResults: true
    maximumWaitTime: '360'


